version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet

artifacts:
  files:
    - index.html
    - react.html
    - babel.html
    - favicon.ico
    - mcliff_resume_2018_04.pdf
    - tms/*
    - styles/*
    - images/*
